name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Japanese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          # MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
          MODEL: gpt-4
          # PROMPT: Please check if there are any confusions or irregularities in the following code diff
          PROMPT: |
            Please provide a thorough and constructive code review of the following NES emulator code diff. In particular, focus on the following points:

            Correctness: Are there any logical errors, emulation inaccuracies, or potential bugs?
            Performance: Could there be any bottlenecks or inefficiencies, especially important in real-time emulation scenarios?
            Maintainability and Readability: Is the code structured and documented in a way that future developers can easily understand and modify it?
            Best Practices: Are there any improvements you would suggest regarding coding standards, design patterns, or NES-specific emulation best practices?
            Potential Pitfalls: Are there any hidden issues (such as timing synchronization or memory boundary cases) that might cause unexpected behavior?

            Please highlight any areas of confusion or irregularity, explain why they might be problematic, and suggest possible fixes or improvements. The code diff is as follows:
            ```diff
            ...
            ```
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
